// code/src/features/expert-teams/expertAvatar.ts
// Static URL helpers for expert avatars. The actual SVG files were
// pre-generated by `scripts/generate-expert-avatars.mjs` and live under
// `public/expert-avatars/<teamId>/<safeName>.svg` — committed to git so
// runtime never needs network or @dicebear at all.

import type { ExpertTeam } from './teams'

const SAFE_RE = /[\\/<>:"|?*\s]/g

/** Mirrors the `safe()` helper in scripts/generate-expert-avatars.mjs. */
function safeName(name: string): string {
  const s = name.replace(SAFE_RE, '_').replace(/^[._]+|[._]+$/g, '')
  return s || 'unnamed'
}

/**
 * Returns a public URL for the expert's pre-generated avatar SVG.
 *
 * Caller passes the team id (from `ExpertTeam.id`) and the expert
 * name (from `ExpertPersona.name`). Returns null when no avatar
 * exists on disk (e.g. open-table teams with dynamically-spawned
 * experts) — caller falls back to `ChatAvatar`'s initial / neutral
 * variant.
 *
 * The `expertNamesByTeam` snapshot below is hand-maintained next to
 * the generator script; if the rosters drift, re-run the script and
 * update this list. We deliberately don't bundle the SVG payload —
 * just the existence check — so the JS bundle stays small.
 */

// Hand-maintained snapshot of which (team, expert) pairs have an
// avatar on disk. Regenerate when teams.ts changes.
const expertHasAvatar = new Set<string>([
  // marketing
  'marketing:品牌负责人',
  'marketing:内容主理人',
  'marketing:增长黑客',
  'marketing:渠道经理',
  // operations
  'operations:CEO',
  'operations:CFO',
  'operations:COO',
  'operations:数据分析师',
  // strategy
  'strategy:战略顾问',
  'strategy:CFO',
  'strategy:法务总监',
  'strategy:CEO 教练',
  // negotiation
  'negotiation:沟通教练',
  'negotiation:异议方角色',
  'negotiation:第三方观察',
  'negotiation:我方代表',
  // retrospective
  'retrospective:业务负责人',
  'retrospective:数据分析师',
  'retrospective:HR',
  'retrospective:流程顾问',
  // investment
  'investment:资深投资人',
  'investment:CFO',
  'investment:行业专家',
  'investment:风控总监',
  // debate
  'debate:正方',
  'debate:反方',
  'debate:主持人',
  'debate:观察员',
])

export function getExpertAvatarUrl(teamId: string, expertName: string): string | null {
  const key = `${teamId}:${expertName}`
  if (!expertHasAvatar.has(key)) return null
  return `/expert-avatars/${teamId}/${safeName(expertName)}.svg`
}

/** Loose normalization: lower-case + strip spaces / hyphens / underscores so
 * 'CEO' matches 'ceo'，'CEO 教练' matches 'ceo-coach'，etc. */
function normalize(s: string): string {
  return s.toLowerCase().replace(/[\s\-_]+/g, '')
}

export function getExpertAvatarUrlForAgent(team: ExpertTeam | null | undefined, agentName: string): string | null {
  if (!team) return null
  const target = normalize(agentName)
  // Try strict match first (cheapest, exact UI display name).
  let expert = team.experts.find((e) => e.agentName === agentName || e.name === agentName)
  if (!expert) {
    // Fuzzy: LLM 经常把"CEO" spawn 成 "ceo"，把"数据分析师" spawn 成 "analyst"。
    // 同时比较 normalize(name) / normalize(agentName)，宽松地兜底。
    expert = team.experts.find((e) => {
      const nName = normalize(e.name)
      const nAgent = e.agentName ? normalize(e.agentName) : ''
      return nName === target || nAgent === target
    })
  }
  if (!expert) return null
  return getExpertAvatarUrl(team.id, expert.name)
}
