// code/src/features/expert-teams/expertAvatar.ts
// Static URL helpers for expert avatars. The actual SVG files were
// pre-generated by `scripts/generate-expert-avatars.mjs` and live under
// `public/expert-avatars/<teamId>/<safeName>.svg` — committed to git so
// runtime never needs network or @dicebear at all.

import {
  EXPERT_TEAMS,
  findExpertByAgentName,
  type ExpertAvatarAtlas,
  type ExpertAvatarSource,
  type ExpertPersona,
  type ExpertTeam,
} from './teams'

const SAFE_RE = /[\\/<>:"|?*\s]/g
const ROUNDTABLE_PLACEHOLDER_AVATARS = [
  '/expert-avatars/roundtable/动态专家一.svg',
  '/expert-avatars/roundtable/动态专家二.svg',
  '/expert-avatars/roundtable/动态专家三.svg',
]
const HR_WORKPLACE_ATLAS_URL = '/expert-avatars/hr-workplace/avatar-atlas.svg'
const HR_WORKPLACE_ATLAS_WIDTH = 384
const HR_WORKPLACE_ATLAS_HEIGHT = 288
const HR_WORKPLACE_AVATAR_TILES = [
  { stableName: 'recruiting-lead', name: '宋知澜', tile: { x: 0, y: 0, w: 96, h: 96 } },
  { stableName: 'hiring-manager', name: '陆承川', tile: { x: 96, y: 0, w: 96, h: 96 } },
  { stableName: 'interview-coach', name: '唐砚宁', tile: { x: 192, y: 0, w: 96, h: 96 } },
  { stableName: 'talent-researcher', name: '赵明川', tile: { x: 288, y: 0, w: 96, h: 96 } },
  { stableName: 'compensation-expert', name: '方予衡', tile: { x: 0, y: 96, w: 96, h: 96 } },
  { stableName: 'performance-advisor', name: '秦砚知', tile: { x: 96, y: 96, w: 96, h: 96 } },
  { stableName: 'hrbp-care', name: '温嘉言', tile: { x: 192, y: 96, w: 96, h: 96 } },
  { stableName: 'legal-advisor', name: '陈景律', tile: { x: 288, y: 96, w: 96, h: 96 } },
  { stableName: 'od-advisor', name: '梁承序', tile: { x: 0, y: 192, w: 96, h: 96 } },
  { stableName: 'hrbp-planning', name: '何远策', tile: { x: 96, y: 192, w: 96, h: 96 } },
  { stableName: 'talent-reviewer', name: '唐识衡', tile: { x: 192, y: 192, w: 96, h: 96 } },
  { stableName: 'people-analyst', name: '周思齐', tile: { x: 288, y: 192, w: 96, h: 96 } },
] satisfies Array<{
  stableName: string
  name: string
  tile: Omit<ExpertAvatarAtlas, 'kind' | 'url' | 'atlasWidth' | 'atlasHeight'>
}>
const HR_WORKPLACE_AVATARS = new Map<string, Omit<ExpertAvatarAtlas, 'kind' | 'url' | 'atlasWidth' | 'atlasHeight'>>(
  HR_WORKPLACE_AVATAR_TILES.flatMap(({ stableName, name, tile }) => [
    [stableName, tile],
    [name, tile],
  ]),
)

export type ExpertAvatarVisual =
  | { kind: 'image'; url: string }
  | ExpertAvatarAtlas
  | { kind: 'text'; text: string }

/** Mirrors the `safe()` helper in scripts/generate-expert-avatars.mjs. */
function safeName(name: string): string {
  const s = name.replace(SAFE_RE, '_').replace(/^[._]+|[._]+$/g, '')
  return s || 'unnamed'
}

/**
 * Returns a public URL for the expert's pre-generated avatar SVG.
 *
 * Caller passes the team id (from `ExpertTeam.id`) and the expert
 * name (from `ExpertPersona.name`). Returns null when no avatar
 * exists on disk (e.g. open-table teams with dynamically-spawned
 * experts) — caller falls back to `ChatAvatar`'s initial / neutral
 * variant.
 *
 * The existence check is derived from `EXPERT_TEAMS` so roster edits do
 * not silently drift from the avatar URL helper. Tests verify matching SVG
 * files exist under `public/expert-avatars/`.
 */
const expertHasAvatar = new Set(
  EXPERT_TEAMS.flatMap((team) =>
    team.experts.map((expert) => `${team.id}:${expert.name}`),
  ),
)

export function getExpertAvatarUrl(teamId: string, expertName: string): string | null {
  const key = `${teamId}:${expertName}`
  if (!expertHasAvatar.has(key)) return null
  return `/expert-avatars/${teamId}/${safeName(expertName)}.svg`
}

function isAtlasAvatar(value: ExpertAvatarSource | null | undefined): value is ExpertAvatarAtlas {
  return Boolean(
    value &&
      typeof value === 'object' &&
      value.kind === 'atlas' &&
      typeof value.url === 'string' &&
      typeof value.x === 'number' &&
      typeof value.y === 'number' &&
      typeof value.w === 'number' &&
      typeof value.h === 'number' &&
      typeof value.atlasWidth === 'number' &&
      typeof value.atlasHeight === 'number',
  )
}

function localHrAtlasAvatar(expert: ExpertPersona): ExpertAvatarAtlas | null {
  const tile = [expert.avatarName, expert.name, expert.agentName]
    .map((key) => key?.trim())
    .find((key): key is string => !!key && HR_WORKPLACE_AVATARS.has(key))
  if (!tile) return null
  const avatarTile = HR_WORKPLACE_AVATARS.get(tile)
  if (!avatarTile) return null
  return {
    kind: 'atlas',
    url: HR_WORKPLACE_ATLAS_URL,
    ...avatarTile,
    atlasWidth: HR_WORKPLACE_ATLAS_WIDTH,
    atlasHeight: HR_WORKPLACE_ATLAS_HEIGHT,
  }
}

function textAvatar(value: ExpertAvatarSource | null | undefined, fallback: string): string {
  if (typeof value === 'string' && value.trim()) return value.trim()
  return Array.from(fallback.trim())[0] ?? '?'
}

function stableIndex(value: string, modulo: number): number {
  let hash = 0
  for (const char of value) {
    hash = (hash * 31 + char.charCodeAt(0)) >>> 0
  }
  return hash % modulo
}

export function getRoundtablePlaceholderAvatarUrl(seed: string | number): string {
  const index = typeof seed === 'number'
    ? seed % ROUNDTABLE_PLACEHOLDER_AVATARS.length
    : stableIndex(seed, ROUNDTABLE_PLACEHOLDER_AVATARS.length)
  return ROUNDTABLE_PLACEHOLDER_AVATARS[index]
}

export function getExpertAvatarVisual(
  teamId: string,
  expert: ExpertPersona,
): ExpertAvatarVisual {
  const localAtlas = localHrAtlasAvatar(expert)
  if (localAtlas) return localAtlas

  const localAvatarUrl = getExpertAvatarUrl(teamId, expert.avatarName ?? expert.name)
  if (localAvatarUrl) return { kind: 'image', url: localAvatarUrl }

  if (isAtlasAvatar(expert.avatar)) return expert.avatar

  return {
    kind: 'text',
    text: expert.avatarText?.trim() || textAvatar(expert.avatar, expert.name) || expert.emoji,
  }
}

export function getExpertAvatarUrlForAgent(team: ExpertTeam | null | undefined, agentName: string): string | null {
  if (!team) return null
  const expert = findExpertByAgentName(team, agentName)
  if (!expert && team.facilitationStyle === 'open') return getRoundtablePlaceholderAvatarUrl(agentName)
  if (!expert) return null
  return getExpertAvatarUrl(team.id, expert.name)
}

export function getExpertAvatarVisualForAgent(
  team: ExpertTeam | null | undefined,
  agentName: string,
): ExpertAvatarVisual | null {
  const expert = findExpertByAgentName(team, agentName)
  if (team && !expert && team.facilitationStyle === 'open') {
    return { kind: 'image', url: getRoundtablePlaceholderAvatarUrl(agentName) }
  }
  if (!team || !expert) return null
  return getExpertAvatarVisual(team.id, expert)
}
