#!/usr/bin/env python3
"""Upload unsigned Windows build artifacts to OSS staging area.

The exe will be downloaded by a local Windows machine for code signing,
then re-uploaded (signed) via sign-windows.ps1.

Env vars required:
  OSS_ACCESS_KEY_ID
  OSS_ACCESS_KEY_SECRET

Usage:
  python scripts/ci-upload-windows-unsigned.py <version> <release_type>
    release_type: beta | release
"""

import os
import sys
from pathlib import Path

import oss2

BUCKET_NAME = "lotus-releases"
ENDPOINT = "https://oss-cn-beijing.aliyuncs.com"
OSS_PREFIX = "aijia"


def upload(bucket, local, key):
    size = os.path.getsize(local)
    print(f"[upload] {os.path.basename(local)} ({size / 1024 / 1024:.1f}MB) -> {key}")
    oss2.resumable_upload(
        bucket, key, str(local),
        multipart_threshold=10 * 1024 * 1024,
        part_size=5 * 1024 * 1024,
        num_threads=4,
    )


def main():
    if len(sys.argv) < 3:
        print("Usage: python ci-upload-windows-unsigned.py <version> <release_type>")
        sys.exit(1)
    version = sys.argv[1].lstrip("v")
    release_type = sys.argv[2]  # beta or release

    key_id = os.environ.get("OSS_ACCESS_KEY_ID", "")
    key_secret = os.environ.get("OSS_ACCESS_KEY_SECRET", "")
    if not key_id or not key_secret:
        print("[error] OSS_ACCESS_KEY_ID / OSS_ACCESS_KEY_SECRET not set")
        sys.exit(1)

    project_root = Path(__file__).resolve().parent.parent
    nsis_dir = project_root / "src-tauri" / "target" / "release" / "bundle" / "nsis"
    exe = nsis_dir / f"AIjia_{version}_x64-setup.exe"

    if not exe.exists():
        print(f"[error] Installer not found: {exe}")
        print(f"  nsis dir contents: {[p.name for p in nsis_dir.iterdir()] if nsis_dir.exists() else '(missing)'}")
        sys.exit(1)

    auth = oss2.Auth(key_id, key_secret)
    bucket = oss2.Bucket(auth, ENDPOINT, BUCKET_NAME)

    # Upload to staging path: aijia/staging/{release_type}/v{version}/
    staging_key = f"{OSS_PREFIX}/staging/{release_type}/v{version}/AIjia_{version}_x64-setup.unsigned.exe"
    upload(bucket, exe, staging_key)

    # Also upload the .sig generated by Tauri (will be regenerated after code signing)
    sig = nsis_dir / f"AIjia_{version}_x64-setup.exe.sig"
    if sig.exists():
        sig_key = f"{OSS_PREFIX}/staging/{release_type}/v{version}/AIjia_{version}_x64-setup.exe.sig.original"
        print(f"[upload] {sig.name} (original, pre-codesign) -> {sig_key}")
        bucket.put_object_from_file(sig_key, str(sig))

    print(f"\n[ok] Windows v{version} ({release_type}) uploaded to staging")
    print(f"     Next: download and sign on local Windows machine")
    print(f"     Then: run sign-windows.ps1 -Version {version} -ReleaseType {release_type}")


if __name__ == "__main__":
    main()
